# Generated by Django 5.0 on 2023-12-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_advocate_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company',
        ),
    ]
