# Generated by Django 5.0 on 2023-12-31 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_name_company_company'),
    ]

    operations = [
    ]
