# Generated by Django 5.0 on 2023-12-31 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20231231_0903'),
    ]

    operations = [
    ]
