# Generated by Django 5.0 on 2023-12-31 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20231231_0904'),
    ]

    operations = [
    ]
