# Generated by Django 5.0 on 2023-12-31 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20231231_0908'),
    ]

    operations = [
    ]
