# Generated by Django 5.0.1 on 2024-01-06 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_advocate_proflepic_advocate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocate',
            name='proflePic',
        ),
        migrations.RemoveField(
            model_name='advocate',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='advocate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.advocate'),
        ),
    ]
