# Generated by Django 5.0.1 on 2024-01-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_advocate_proflepic_remove_advocate_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='proflePic',
            field=models.ImageField(default='default.png', upload_to='Profile_pics'),
        ),
    ]
