# Generated by Django 5.0 on 2024-01-06 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_advocate_proflepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='proflePic',
            new_name='profilePic',
        ),
        migrations.RemoveField(
            model_name='advocate',
            name='proflePic',
        ),
        migrations.AddField(
            model_name='advocate',
            name='profilePic',
            field=models.ImageField(default='default.png', upload_to='Profile_pics'),
        ),
    ]
