# Generated by Django 5.0.1 on 2024-01-06 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_proflepic_profile_profilepic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocate',
            name='company',
        ),
        migrations.CreateModel(
            name='Advocates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advocates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.advocate')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company')),
            ],
        ),
    ]
