# Generated by Django 5.0.1 on 2024-01-06 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_remove_advocate_company_advocates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advocates',
            old_name='advocates',
            new_name='advocate',
        ),
    ]
