# Generated by Django 5.0.1 on 2024-01-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_advocates_advocates_advocate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advocates',
            new_name='AdvocateAll',
        ),
    ]
