# Generated by Django 5.0.1 on 2024-01-06 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_advocateall_company_advocate_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocate',
            name='company',
        ),
        migrations.AddField(
            model_name='advocateall',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.company'),
        ),
    ]
