# Generated by Django 5.0.1 on 2024-01-06 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_advocateall_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocateall',
            name='company',
        ),
    ]
