# Generated by Django 5.0.1 on 2024-01-07 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_advocateall_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocateall',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.company'),
        ),
    ]
