# Generated by Django 5.0.1 on 2024-01-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_advocateall_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocateall',
            name='company',
        ),
    ]
