# Generated by Django 5.0.1 on 2024-01-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_rename_advocates_advocateall_advocate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advocateall',
            old_name='advocate',
            new_name='advocates',
        ),
    ]
