# Generated by Django 5.0.1 on 2024-01-07 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_advocate_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='advocate',
        ),
        migrations.CreateModel(
            name='AdvocateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePic', models.ImageField(default='default.png', upload_to='Profile_pics')),
                ('advocate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.advocate')),
            ],
        ),
    ]
