# Generated by Django 5.0.1 on 2024-01-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_remove_profile_advocate_advocateprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='default.png', upload_to='media/Profile_pics'),
        ),
    ]
