# Generated by Django 5.0.1 on 2024-01-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_profile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocateprofile',
            name='profilePic',
            field=models.ImageField(default='default.png', upload_to='media/Profile_pics'),
        ),
    ]
