# Generated by Django 5.0.1 on 2024-01-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_advocateprofile_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocateprofile',
            name='profilePic',
            field=models.ImageField(default='media/default.png', upload_to='Profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='media/default.png', upload_to='Profile_pics'),
        ),
    ]
