# Generated by Django 5.0.1 on 2024-01-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_advocateprofile_profilepic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocateprofile',
            name='profilePic',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
